version: '3'
services:
  sandbox-wcs-api:
    container_name: sandbox-wcs-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - sandbox-wcs-network

volumes:
  postgres:


networks:
  sandbox-wcs-network:
    name: sandbox-wcs
    driver: bridge
