name: Build WCS Stack

on:
  - workflow_dispatch
  - push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '[ACTION] | Clone build wcs action'
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-wcs-action
          ref: 2.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./build-wcs-action

      - name: '[ACTION] | Run build wcs action'
        uses: './build-wcs-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
